### ISSUE TITLE
Minor issues in evaluation report created with v10

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/Sufentanil-Model#12]
Attached are some comments of the evaluation report for sufentanil created with v10
[Sufentanil_evaluation_report_AD.pdf](https://github.com/Open-Systems-Pharmacology/Sufentanil-Model/files/7337569/Sufentanil_evaluation_report_AD.pdf)

@Incei

**Comment by Incei** [comment]
revised content and created new pull request

**Comment by Yuri05** [comment]
Fixed with last PR
